export default {
  // IMAGE_URL: 'http://43.204.142.108:4000/',
  // Images moved from S3 to Cloudflare R2; new uploads return 403 on the old S3 URL.
  // IMAGE_URL: 'https://s3.ap-south-1.amazonaws.com/gajragro2.fieldkonnect.io/',
  IMAGE_URL: 'https://gajragro.fieldkonnect.io/',
  // IMAGE_URL: 'https://s3.ap-south-1.amazonaws.com/gajragro.fieldkonnect.io/',
  // IMAGE_URL: 'https://apis.fieldkonnect.io/',
  // IMAGE_URL_TEST: 'http://13.232.29.75:4000/',
  // IMAGE_URL: 'http://13.232.29.75:4000/',
  APP_LOGO: require('../../assets/images/login_banner.png'),
  BACK: require('../../assets/images/back_arrow.png'),
  ADD: require('../../assets/images/add.png'),
  UPLOAD: require('../../assets/images/upload.png'),
  CURRENT_LOCATION: require('../../assets/images/current_location.png'),
  DROP_DOWN: require('../../assets/images/drop_down.png'),
  ICON_ONE: require('../../assets/images/icon_one.png'),
  ICON_TWO: require('../../assets/images/icon_two.png'),
  ICON_THREE: require('../../assets/images/icon_three.png'),
  RUPEE: require('../../assets/images/rupee.png'),
  EDIT: require('../../assets/images/eddit.png'),
  ALERT: require('../../assets/images/alert_circle.png'),
  GALLERY: require('../../assets/images/gallery.png'),
  REFER_FRIEND: require('../../assets/images/friendship.png'),
  COPY: require('../../assets/images/copy.png'),
  REEDEM_DEC: require('../../assets/images/redeemdec.png'),
  USER: require('../../assets/images/user.png'),
  // EYE_OFF: require('../../assets/images/eye_off.png'),
  // VISITING_CARD: require('../../assets/images/visiting_card.png'),
  // ADD_IMAGES: require('../../assets/images/add_images.png'),
  // MAP: require('../../assets/images/maps.png'),
  // CHECK_BOX: require('../../assets/images/check_box.png'),
  // SQUARE: require('../../assets/images/square.png'),
  // LOGIN: require('../../assets/images/login.png'),
  // static_image_banner: require('../../assets/images/Banner.jpg'),
  // MARKER: require('../../assets/images/map_pin.png'),
  // CAMERA: require('../../assets/images/camera.png'),
  // QR_CODE: require('../../assets/images/qr_code.png'),
  // HOME: require('../../assets/images/home.png'),
  // HISTORY: require('../../assets/images/coupon.png'),
  // COUPON: require('../../assets/images/history.png'),
  // HOMEE: require('../../assets/images/homee.png'),
  // LEADERBOARD: require('../../assets/images/leaderboard.png'),
  // CONTEST: require('../../assets/images/contest.png'),
  // CATALAOGE: require('../../assets/images/catalogue.png'),
  // ANNOUNCEMENT: require('../../assets/images/announcements.png'),
  // KNOWLEDGE: require('../../assets/images/knowledge.png'),
  // BACK_ARROW: require('../../assets/images/arrw_left.png'),
  // LOGOUT: require('../../assets/images/logout.png'),
  // DIAMOND: require('../../assets/images/diamond.png'),
  // COUPONN: require('../../assets/images/couponn.png'),
  // CALENDAR: require('../../assets/images/calendar.png'),
  // HISTORYY: require('../../assets/images/history.png'),
  // WALLET: require('../../assets/images/paytm_wallet.png'),
  // VOUCHERS: require('../../assets/images/vouchers.png'),
  // UPI: require('../../assets/images/upi_id.png'),
  // NEFT: require('../../assets/images/neft.png'),
  // GIFTS: require('../../assets/images/gifts.png'),
  // VOLUNTEER: require('../../assets/images/volunteer.png'),
  // NOTIFICATION_BELL: require('../../assets/images/notificationbell.png'),
  // BEST_SELLER: require('../../assets/images/best_seller.png'),
  // GIFTS_CARD: require('../../assets/images/gifts_card.png'),
  // PAYTM: require('../../assets/images/paytmlogo.png'),
  // NEFT_CARD: require('../../assets/images/neftt.png'),
  // VOUCHERS_CARD: require('../../assets/images/vouchers_card.png'),
  // HAMMENU: require('../../assets/images/hamburger-menu-icon.png'),
  // BHIMUPI: require('../../assets/images/bhimupi.png'),
  // UPI_PNG: require('../../assets/images/upi.png'),
  // GOOGLEUPI: require('../../assets/images/googleupi.png'),
  // OTHERUPI: require('../../assets/images/otherupii.png'),
  // PHONEPE: require('../../assets/images/pp4.png'),
  // SECURELOCK: require('../../assets/images/securelock.png'),
  // SUCCESSANIM: require('../../assets/images/success.json'),
  // GIFT_ICON: require('../../assets/images/gift_icon.png'),
  // GiftHistory: require('../../assets/images/GiftHistory.png'),
  // CIRCULAR_BACK: require('../../assets/images/cicularhistory.png'),
  // PhoneIcon: require('../../assets/images/phone.png'),
  // MainIcon: require('../../assets/images/mail.png'),
  // Whatsapp: require('../../assets/images/whatsapp.png'),
  // Linkedin: require('../../assets/images/linkedin.png'),
  // Twitter: require('../../assets/images/twitter.png'),
  // Instagram: require('../../assets/images/instagram.png'),
  // Gmail: require('../../assets/images/gmail.png'),
  // Facebook: require('../../assets/images/facebook.png'),
  // Youtube: require('../../assets/images/youtube.png'),
};
