const navigationStrings = {
  LOGIN: 'Login',
  STARTINGSCREEN: 'StartingScreen',
  HOME: 'Home',
  LOCATION: 'Location',
  UPDATE_LOCATION: 'UpdateLocation',
  SIGN_UP_ONE: 'SignUpOne',
  SIGN_UP_TWO: 'SignUpTwo',
  SIGN_UP_THREE: 'SignUpThree',
  COUPON: 'Coupon',
  COUPON_SCAN: 'Coupon Scan',
  HISTORY: 'History',
  PROFILE: 'Profile',
  TRANSACTION: 'Transaction',
  PRODUCT: 'Product',
  LEADERBOARD: 'Leaderboard',
  Contests: 'Contests',
  ANNOUNCEMENTS: 'Announcements',
  STORIES: 'Stories',
  REFER: 'ReferEarn',
  KNOWLEDGE: 'Knowledge',
  SUPPORT: 'Support',
  DAMAGE: 'Damage',

  REDEMPTIONFINAL: 'RedemptionFinal',
  // REDEMPTION: 'Redemption',
  // REDEMPTION_ONE: 'RedemptionOne',
  SIDEDRAWER: 'CustomerDrawer',
  SIDEMENU: 'SideMenu',
  SUCCESSPOINTS: 'SuccessPoints',
  REWARDSUCCESS: 'RewardSuccess',
  REDEEMHISTORY: 'Redeem History',
  REDEMPTIONDETAIL: 'RedemptionDetail',
  Payout: 'PayoutRequest',
};

export default navigationStrings;
